---
name: CPAN-Test-Dummy-Perl5-Build-Fails
version: 1.02
author:
  - Andreas Koenig
abstract: CPAN Test Dummy
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  CPAN::Test::Dummy::Perl5::Build::Fails:
    file: lib/CPAN/Test/Dummy/Perl5/Build/Fails.pm
    version: 1.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
